#ifndef __CARD_ENUMS_H__
#define __CARD_ENUMS_H__

#include "utils/enum_variant.h"
#include "utils/reflector.h"

#include "card_serial.h"

namespace banggame {

    using namespace enums::flag_operators;

    DEFINE_ENUM_DATA(card_suit,
        (none,      u8"")
        (hearts,    u8"\u2665")
        (diamonds,  u8"\u2666")
        (clubs,     u8"\u2663")
        (spades,    u8"\u2660")
    )

    DEFINE_ENUM_DATA(card_rank,
        (none,      "")
        (rank_A,    "A")
        (rank_2,    "2")
        (rank_3,    "3")
        (rank_4,    "4")
        (rank_5,    "5")
        (rank_6,    "6")
        (rank_7,    "7")
        (rank_8,    "8")
        (rank_9,    "9")
        (rank_10,   "10")
        (rank_J,    "J")
        (rank_Q,    "Q")
        (rank_K,    "K")
    )

    DEFINE_STRUCT(card_sign,
        (card_suit, suit)
        (card_rank, rank),

        explicit operator bool () const {
            return suit != card_suit::none && rank != card_rank::none;
        }
    )
    
    DEFINE_ENUM_FLAGS_FWD_TYPES(card_expansion_type,
        (dodgecity)
        (goldrush,              ruleset_goldrush)
        (armedanddangerous,     ruleset_armedanddangerous)
        (valleyofshadows,       ruleset_valleyofshadows)
        (highnoon)
        (fistfulofcards)
        (wildwestshow)
        (thebullet)
        (canyondiablo,          ruleset_canyondiablo)
    )

    constexpr auto unofficial_expansions = card_expansion_type::canyondiablo;

    DEFINE_ENUM(card_color_type,
        (none)
        (brown)
        (blue)
        (green)
        (black)
        (orange)
    )

    DEFINE_ENUM(player_role,
        (unknown)
        (sheriff)
        (deputy)
        (outlaw)
        (renegade)
        (deputy_3p)
        (outlaw_3p)
        (renegade_3p)
    )

    DEFINE_ENUM_FLAGS(target_player_filter,
        (any)
        (dead)
        (self)
        (notself)
        (notsheriff)
        (range_1)
        (range_2)
        (reachable)
    )

    DEFINE_ENUM_FLAGS(target_card_filter,
        (table)
        (hand)
        (blue)
        (black)
        (clubs)
        (bang)
        (bangcard)
        (missed)
        (beer)
        (bronco)
        (cube_slot)
        (can_repeat)
        (can_target_self)
    )

    DEFINE_ENUM_TYPES(target_type,
        (none)
        (player,                serial::player)
        (conditional_player,    serial::opt_player)
        (card,                  serial::card)
        (extra_card,            serial::opt_card)
        (players)
        (fanning_targets,       std::vector<serial::player>)
        (cards,                 std::vector<serial::card>)
        (cards_other_players,   std::vector<serial::card>)
        (select_cubes,          std::vector<serial::card>)
        (self_cubes)
    )

    using play_card_target = enums::enum_variant<target_type>;
    using target_list = std::vector<play_card_target>;

    DEFINE_ENUM(card_deck_type,
        (none)
        (main_deck)
        (character)
        (role)
        (goldrush)
        (highnoon)
        (fistfulofcards)
        (wildwestshow)
    )

    DEFINE_ENUM(pocket_type,
        (none)
        (player_hand)
        (player_table)
        (player_character)
        (player_backup)
        (main_deck)
        (discard_pile)
        (selection)
        (shop_deck)
        (shop_discard)
        (shop_selection)
        (hidden_deck)
        (scenario_deck)
        (scenario_card)
        (button_row)
    )

    DEFINE_ENUM(card_modifier_type,
        (none)
        (bangmod)
        (discount)
        (leevankliff)
        (shopchoice)
        (belltower)
        (bandolier)
    )

    DEFINE_ENUM_FLAGS(effect_flags,
        (is_bang)
        (play_as_bang)
        (escapable)
        (single_target)
        (multi_target)
        (auto_respond)
    )
    
    DEFINE_ENUM_FWD_TYPES(effect_type,
        (none)
        (mth_add)
        (play_card_action,      effect_play_card_action)
        (max_usages,            effect_max_usages)
        (pass_turn,             effect_pass_turn)
        (resolve,               effect_resolve)
        (bang,                  effect_bang)
        (bangcard,              effect_bangcard)
        (banglimit,             effect_banglimit)
        (missed,                effect_missed)
        (barrel,                effect_barrel)
        (discard,               effect_discard)
        (destroy,               effect_destroy)
        (startofturn,           effect_startofturn)
        (while_drawing,         effect_while_drawing)
        (reset_drawing,         effect_reset_drawing)
        (end_drawing,           effect_end_drawing)
        (steal,                 effect_steal)
        (duel,                  effect_duel)
        (beer,                  effect_beer)
        (heal,                  effect_heal)
        (heal_notfull,          effect_heal_notfull)
        (indians,               effect_indians)
        (draw,                  effect_draw)
        (draw_discard,          effect_draw_discard)
        (draw_to_discard,       effect_draw_to_discard)
        (draw_one_less,         effect_draw_one_less)
        (generalstore,          effect_generalstore)
        (deathsave,             effect_deathsave)
        (backfire,              effect_backfire)
        (bandidos,              effect_bandidos)
        (aim,                   effect_aim)
        (poker,                 effect_poker)
        (tornado,               effect_tornado)
        (damage,                effect_damage)
        (saved,                 effect_saved)
        (escape,                effect_escape)
        (sell_beer,             effect_sell_beer)
        (discard_black,         effect_discard_black)
        (add_gold,              effect_add_gold)
        (pay_gold,              effect_pay_gold)
        (rum,                   effect_rum)
        (goldrush,              effect_goldrush)
        (forced_play,           effect_forced_play)
        (forced_equip,          effect_forced_equip)
        (pay_cube,              effect_pay_cube)
        (add_cube,              effect_add_cube)
        (rust,                  effect_rust)
        (doublebarrel,          effect_doublebarrel)
        (thunderer,             effect_thunderer)
        (buntlinespecial,       effect_buntlinespecial)
        (bigfifty,              effect_bigfifty)
        (bandolier,             effect_bandolier)
        (move_bomb,             effect_move_bomb)
        (tumbleweed,            effect_tumbleweed)
        (sniper,                effect_sniper)
        (ricochet,              effect_ricochet)
        (ranch,                 effect_ranch)
        (greygory_deck,         effect_greygory_deck)
        (lemonade_jim,          effect_lemonade_jim)
        (josh_mccloud,          effect_josh_mccloud)
        (frankie_canton,        effect_frankie_canton)
        (evelyn_shebang,        effect_evelyn_shebang)
        (al_preacher,           effect_al_preacher)
        (ms_abigail,            effect_ms_abigail)
        (graverobber,           effect_graverobber)
        (mirage,                effect_mirage)
        (disarm,                effect_disarm)
        (sacrifice,             effect_sacrifice)
        (lastwill,              effect_lastwill)
    )

    DEFINE_ENUM_FWD_TYPES(equip_type,
        (none)
        (mustang,               equip_mustang)
        (scope,                 equip_scope)
        (predraw_check,         equip_predraw_check)
        (jail,                  equip_jail)
        (dynamite,              equip_dynamite)
        (horse,                 equip_horse)
        (weapon,                equip_weapon)
        (volcanic,              equip_volcanic)
        (pixie_pete,            equip_pixie_pete)
        (apache_kid,            equip_apache_kid)
        (bart_cassidy,          equip_bart_cassidy)
        (ghost,                 equip_ghost)
        (snake,                 equip_snake)
        (shotgun,               equip_shotgun)
        (bounty,                equip_bounty)
        (el_gringo,             equip_el_gringo)
        (lucky_duke,            equip_lucky_duke)
        (luckycharm,            equip_luckycharm)
        (gunbelt,               equip_gunbelt)
        (initialcards,          equip_initialcards)
        (wanted,                equip_wanted)
        (bomb,                  equip_bomb)
        (tumbleweed,            equip_tumbleweed)
        (bronco,                equip_bronco)
        (calamity_janet,        equip_calamity_janet)
        (black_jack,            equip_black_jack)
        (kit_carlson,           equip_kit_carlson)
        (claus_the_saint,       equip_claus_the_saint)
        (bill_noface,           equip_bill_noface)
        (slab_the_killer,       equip_slab_the_killer)
        (suzy_lafayette,        equip_suzy_lafayette)
        (vulture_sam,           equip_vulture_sam)
        (johnny_kisch,          equip_johnny_kisch)
        (bellestar,             equip_bellestar)
        (greg_digger,           equip_greg_digger)
        (herb_hunter,           equip_herb_hunter)
        (molly_stark,           equip_molly_stark)
        (tequila_joe,           equip_tequila_joe)
        (vera_custer,           equip_vera_custer)
        (tuco_franziskaner,     equip_tuco_franziskaner)
        (colorado_bill,         equip_colorado_bill)
        (henry_block,           equip_henry_block)
        (big_spencer,           equip_big_spencer)
        (teren_kill,            equip_teren_kill)
        (gary_looter,           equip_gary_looter)
        (john_pain,             equip_john_pain)
        (youl_grinner,          equip_youl_grinner)
        (don_bell,              equip_don_bell)
        (dutch_will,            equip_dutch_will)
        (madam_yto,             equip_madam_yto)
        (greygory_deck,         equip_greygory_deck)
        (lemonade_jim,          equip_lemonade_jim)
        (mick_defender,         equip_mick_defender)
        (julie_cutter,          equip_julie_cutter)
        (bloody_mary,           equip_bloody_mary)
        (red_ringo,             equip_red_ringo)
        (al_preacher,           equip_al_preacher)
        (ms_abigail,            equip_ms_abigail)
        (blessing,              equip_blessing)
        (curse,                 equip_curse)
        (thedaltons,            equip_thedaltons)
        (thedoctor,             equip_thedoctor)
        (trainarrival,          equip_trainarrival)
        (thirst,                equip_thirst)
        (highnoon,              equip_highnoon)
        (shootout,              equip_shootout)
        (invert_rotation,       equip_invert_rotation)
        (reverend,              equip_reverend)
        (hangover,              equip_hangover)
        (sermon,                equip_sermon)
        (ghosttown,             equip_ghosttown)
        (handcuffs,             equip_handcuffs)
        (ranch,                 equip_ranch)
        (ambush,                equip_ambush)
        (lasso,                 equip_lasso)
        (judge,                 equip_judge)
        (peyote,                equip_peyote)
        (russianroulette,       equip_russianroulette)
        (abandonedmine,         equip_abandonedmine)
        (deadman,               equip_deadman)
        (fistfulofcards,        equip_fistfulofcards)
        (weapon_base,           equip_weapon_base)
        (packmule,              equip_packmule)
        (indianguide,           equip_indianguide)
        (taxman,                equip_taxman)
        (prompt_on_self_equip,  equip_prompt_on_self_equip)
        (brothel,               equip_brothel)
        (lastwill,              equip_lastwill)
        (newidentity,           equip_newidentity)
        (lawofthewest,          equip_lawofthewest)
        (vendetta,              equip_vendetta)
    )

    DEFINE_ENUM_FWD_TYPES(mth_type,
        (none)
        (play_as_bang,          handler_play_as_bang)
        (play_as_gatling,       handler_play_as_gatling)
        (doc_holyday,           handler_doc_holyday)
        (flint_westwood,        handler_flint_westwood)
        (draw_multi,            handler_draw_multi)
        (heal_multi,            handler_heal_multi)
        (flintlock,             handler_flintlock)
        (duck,                  handler_duck)
        (squaw,                 handler_squaw)
        (red_ringo,             handler_red_ringo)
        (card_sharper,          handler_card_sharper)
        (lastwill,              handler_lastwill)
    )

    DEFINE_ENUM(tag_type,
        (none)
        (temp_card)
        (ghost_card)
        (confirm)
        (skip_logs)
        (hidden)
        (discard_if_two_players)
        (bangcard)
        (missedcard)
        (play_as_bang)
        (beer)
        (indians)
        (drawing)
        (weapon)
        (horse)
        (repeatable)
        (auto_confirm)
        (auto_confirm_red_ringo)
        (shopchoice)
        (last_scenario_card)
        (peyote)
        (handcuffs)
        (buy_cost)
        (max_hp)
        (bronco)
    )

}

#endif