#!/usr/bin/env python

import subprocess
import itertools
import sys
import yaml

if __name__ == '__main__':
    with subprocess.Popen('git show :src/cards/bang_cards.yml', stdout=subprocess.PIPE) as proc:
        bang_cards_data = yaml.safe_load(proc.stdout)

    for card in itertools.chain.from_iterable(bang_cards_data.values()):
        if 'tags' in card and 'testing' in card['tags']:
            print("Error: found 'testing' tag in",
                card['name'] if 'name' in card else '(unnamed card)')
            sys.exit(1)
