#!/usr/bin/env python

import itertools
import json
from pathlib import Path

if __name__ == '__main__':
    with open(Path(__file__).parent / '../resources/bang_cards.json', 'r') as file:
        bang_cards_json = json.load(file)

    for card in itertools.chain.from_iterable(bang_cards_json.values()):
        if 'tags' in card and 'testing' in card['tags']:
            print("Error: found 'testing' tag in ", card['name'] if 'name' in card else '(unnamed card)')
            exit(1)