#!/usr/bin/env python

import itertools
import yaml
from pathlib import Path

if __name__ == '__main__':
    with open(Path(__file__).parent / '../src/cards/bang_cards.yml', 'r') as file:
        bang_cards_data = yaml.safe_load(file)

    for card in itertools.chain.from_iterable(bang_cards_data.values()):
        if 'tags' in card and 'testing' in card['tags']:
            print("Error: found 'testing' tag in ", card['name'] if 'name' in card else '(unnamed card)')
            exit(1)