fistfulofcards:
  - name: AMBUSH
    image: 05_agguato
    equip:
      - ambush
  - name: SNIPER
    image: 05_cecchino
    effects:
      - discard cards(2) self | hand bang
      - sniper player reachable notself
  - name: DEAD_MAN
    image: 05_deadman
    expansion: ghost_cards
    equip:
      - deadman
    tags:
      - ghost_card
  - name: BLOOD_BROTHERS
    image: 05_fratellidisangue
    equip:
      - blood_brothers
    responses:
      - can_play_card
      - blood_brothers player notself
  - name: THE_JUDGE
    image: 05_ilgiudice
    equip:
      - judge
  - name: LASSO
    image: 05_lazo
    equip:
      - lasso
  - name: LAW_OF_THE_WEST
    image: 05_leggedelwest
    equip:
      - lawofthewest
  - name: HARD_LIQUOR
    image: 05_liquoreforte
    responses:
      - skip_drawing
      - no_cards_drawn
      - heal_notfull
  - name: ABANDONED_MINE
    image: 05_minieraabbandonata
    equip:
      - abandonedmine
  - name: PEYOTE
    image: 05_peyote
    equip:
      - peyote
    modifier_response: card_choice
    responses:
      - none
    tags:
      - card_choice(5)
      - preselect
      - skip_logs
  - name: RANCH
    image: 05_ranch
    equip:
      - ranch
    responses:
      - ranch
      - none max_cards self | hand
    mth_response: ranch(1)
    tags:
      - preselect
  - name: RICOCHET
    image: 05_rimbalzo
    effects:
      - discard card self | hand bang
      - ricochet card notself | table
  - name: RUSSIAN_ROULETTE
    image: 05_rouletterussa
    equip:
      - russianroulette
  - name: VENDETTA
    image: 05_vendetta
    equip:
      - vendetta
  - name: A_FISTFUL_OF_CARDS
    image: 05_perunpugnodicarte
    equip:
      - fistfulofcards
    tags:
      - last_scenario_card

hidden:
  - name: PEYOTE_RED
    image: fistfulofcards/05_peyote_rosso
    responses:
      - card_choice
      - peyote(&card_sign::is_red)
    tags:
      - card_choice(5)
  - name: PEYOTE_BLACK
    image: fistfulofcards/05_peyote_nero
    responses:
      - card_choice
      - peyote(&card_sign::is_black)
    tags:
      - card_choice(5)