legends:
  - name: BART_CASSIDY
    image: 23_bart_cassidy
    equip:
      - bart_cassidy(2)
  - name: BLACK_JACK
    image: 23_black_jack
    # TODO - on_draw_from_deck: rivela in loop finche' il "valore" non e' piu' di 21
  - name: CALAMITY_JANET
    image: 23_calamity_janet
    equip:
      - treat_as_bang(2)
    effects:
      - banglimit
      - set_playing card self | hand not_bangcard
      - none player reachable notself
    mth_effect: play_as_bang(1,2)
    responses:
      - set_playing card self | hand not_missedcard
    mth_response: play_as_missed(0)
    tags:
      - play_as_bang
      - banglimit
  - name: EL_GRINGO
    image: 23_el_gringo
    # TODO - equip_el_gringo + equip_el_grindo_legend
    # equip_el_gringo_legend: on_hit -> pesca la origin_card
    tags:
      - max_hp(3)
  - name: JESSE_JONES
    image: 23_jesse_jones
    # TODO - effect_jesse_jones_legend player not_empty_hand:
    # sposta carte di target in selection (owner = origin)
    # request_jesse_jones_legend: pickable - on_pick -> draw target_card, ridai carte a owner, draw
  - name: JOURDONNAIS
    image: 23_jourdonnais
    # TODO - equip_jourdonnais_legend
    # add_listener apply_escapable_modifier -> value = 2
    # effect_jourdonnais (can_play: request_bang || escapable)
    # draw_check (j, q, k, a -> pop_request)
  - name: KIT_CARLSON
    image: 23_kit_carlson
    equip:
    - kit_carlson_legend
    responses:
      - kit_carlson_legend_response
      - none card | selection
      - none player notself
    mth_response: gift_card_selection(1,2)
    tags:
      - preselect
  - name: LUCKY_DUKE
    image: 23_lucky_duke
    equip:
      - lucky_duke_legend
  - name: PAUL_REGRET
    image: 23_paul_regret
    # TODO - mustang + equip_paul_regret_legend
    # equip_paul_regret_legend: get_error quando si gioca bang, errore se non ha altre carte in mano
    # on_play_bang (nuovo evento) request_discard
  - name: PEDRO_RAMIREZ
    image: 23_pedro_ramirez
    # TODO equip_pedro_ramirez_legend: on_draw_from_deck: draw one from discards
    # (add_action con priority=-8 -- da diminuire altre azioni da -8 a -9)
  - name: ROSE_DOOLAN
    image: 23_rose_doolan
    # equip:
      # - rose_doolan_legend # TODO vedi tutti a distanza 1
    effects:
      - max_usages(1)
      - discard card self | blue
      - steal card range_1
  - name: SID_KETCHUM
    image: 23_sid_ketchum
    # TODO effetto base + equip_sid_ketchum_legend
    # on_heal (nuovo evento) attiva request: pickable_player -> bang (una volta per turno) 
  - name: SLAB_THE_KILLER
    image: 23_slab_the_killer
    # TODO apply_bang_modifier : unavoidable = true
    # puo' rimuovere l'ultimo punto vita quando rivendica un'impresa (da capire)
  - name: SUZY_LAFAYETTE
    image: 23_suzy_lafayette
    # TODO equip_suzy_lafayette_legend: condizione ncards < 2
  - name: VULTURE_SAM
    image: 23_vulture_sam
    # TODO equip_vulture_sam + equip_vulture_sam_legend
    # on_player_death: cambia personaggio a versione base + set_hp(4)
  - name: WILLY_THE_KID
    image: 23_willy_the_kid
    # TODO volcanic + bang gratis da personaggio se non ha rivendicato impresa
    # conta come feat attivata per il check di "vantare impresa"

feats:
  - name: FIFTY_GUNS
    image: 23_cinquanta_pistole
    # TODO on_destroy_card se target_card ha tag weapon -> attiva feat
  - name: WOUNDED_PRIDE
    image: 23_ferito_nell_orgoglio
    # TODO on_missed se flag is_bang e origin == p -> attiva feat
  - name: OLD_WEST_GANG
    image: 23_gang_del_vecchio_west
    # TODO on_hit se origin == p && target != p
    #  add_listener (target_card, 5) track_damaged_player first_target ->
    #    se first_target == null -> set first_target
    #    se first_target != target -> attiva feat
    # on_turn_end: clear listener (target_card, 5)
  - name: BOTTLENECK
    image: 23_il_collo_di_bottiglia
    # TODO on_destroy_card se target_card ha tag beer -> attiva feat
    # crocevia: discard card self | hand beer -> attiva feat
  - name: THE_CHUCK_A_LUCK
    image: 23_il_mulino_d_oro
    # TODO on_destroy_card se target_card ha tag bangcard -> attiva feat
    # crocevia: discard card self | hand bangcard -> attiva feat
  - name: '3_15_TO_YOOMA'
    image: 23_il_treno_per_yooma
    # TODO on_draw_check_start (nuovo evento) -> attiva feat
  - name: IN_GOOD_COMPANY
    image: 23_in_buona_compagnia
    # TODO da capire come tenere traccia
    # on_destroy_card se scarti una carta con stesso nome di ultima carta giocata in history
    # on_play_card (nuovo evento?) se giochi una carta con stesso nome di ultima carta scartata
    # crocevia: in_good_company card self | hand -> feat
    #  effect_in_good_company (discard): error se target_card non ha stesso nome di ultima carta scartata
  - name: THE_LAST_HERO
    image: 23_l_ultimo_eroe
    # TODO on_destroy_card se target_card blue -> attiva feat
    # crocevia: discard card self | hand blue -> attiva feat
  - name: THE_MAN_WITH_NO_NAME
    image: 23_l_uomo_senza_nome
    # TODO on_hit se hp > 0 -> attiva feat
    # crocevia: damage -> attiva feat
  - name: WILHELM_SCREAM
    image: 23_l_urlo_di_wilhelm
    # TODO on_play_bang (nuovo evento) se count_distance(origin, target) >= 2 -> feat
  - name: SCRUGS_BALLAD
    image: 23_la_ballata_di_scrugs
    # TODO on_duel_hit (nuovo evento) se p == target -> feat
  - name: BORDERLANDS
    image: 23_la_frontiera
    # TODO crocevia: borderlands
    # effect_borderlands: scarta tutto dalla mano -> feat
  - name: THE_OREGON_TRAIN
    image: 23_la_pista_dell_oregon
    # TODO crocevia: - add_draw_card -> feat
  - name: A_THOUSAND_WAYS_TO_DIE
    image: 23_mille_modi_per_morire
    # TODO crocevia: - thousand_ways cards(2) self
    # effect_thousand_ways: get_error = una delle carte e' mancato
    # on_play: rivela carte -> feat
  - name: FOR_A_FEW_CARDS_MORE
    image: 23_per_qualche_carta_in_piu
    # TODO on_turn_end:
    # request_few_cards_more: pickable and resolvable
    # on_pick -> scarta carta -> feat
    # on_resolve -> dismiss
  - name: A_QUICK_DEATH
    image: 23_una_morte_veloce
    # TODO on_hit se hp == max_hp e flags is_bang -> feat

button_row:
  - name: ESCAPE_JAIL
    responses:
      - discard card self | hand hearts
      - escape_jail
    
# TODO ruleset di legends
#
# attiva feat:
#  NOTE da tenere traccia, deve succedere max una volta per turno
#  request_perform_feat: pickable su carta feat "attivata" e resolvable (2 - dismiss)
#    on_resolve -> pop_request
#    on_pick: effect_perform_feat
#
#  effect_perform_feat:
#  can_play: se nessuna impresa compiuta
#  on_play:
#   se NON sei leggenda - compiere impresa:
#     -> sposta max 2 fame da character a carta feat
#     -> track feat compiuta
#   se SEI leggenda e c'e' almeno un'altra leggenda - rivendicare impresa:
#     -> pop_request, request_claim_feat: pickable su player leggenda e hp > 1
#     on_pick:
#      -> pop_request
#      -> damage target
#      -> discard feat (rimuovi fame)
#      -> draw feat (shuffle se necessario)
#      -> track feat compiuta
#
# vantare impresa:
#  on_turn_end (da capire priority) -> se nessuna impresa compiuta e personaggio non leggenda:
#   -> request_boast_feat: pickable su mazzo feat + resolvable (2 - dismiss)
#    on_resolve -> pop_request
#    on_pick -> draw feat (shuffle se necessario)
#      -> se n feats > 4: request_discard_feat: pickable su feats con max fame (auto_pick)
#         on_pick -> discard feat (rimuovi fame)
#   -> request_boast_add_fame: pickable su feat con 0 fame "del tuo tipo"
#     TODO N tipi diversi di token
#      on_pick -> move fame
#
# diventare leggenda:
#  button_row effect_become_legend -> can_play = se hai 0 fame e personaggio non leggenda
#    (note: check vulture sam)
#   on_play: swap personaggio con equivalente in lista legends con stesso nome
#   se hp < 3 -> set_hp 3