rulesets:
  - name: vlcata

characters:
  - name: BEJCEK
    image: 29_bejcek
    effects:
      - max_usages(3)
      - discard card self | hand
      - draw(1)

  - name: PATKA
    image: 29_patka
    effects:
      - max_usages(1)
      - discard card self | hand
      - draw(2)

  - name: ANEZKA
    image: 29_anezka
    effects:
      - max_usages(1)
      - discard cards(2) self
      - heal player alive

  - name: TERKA_P
    image: 29_terka_p
    responses:
      - deathsave
      - discard cards(3) self | hand
      - heal

  - name: JULKA
    image: 29_julka
    equip:
      - initial_cards(5)

  - name: HARRY
    image: 29_harry
    effects:
      - max_usages(2)
      - discard card self | hand
      - steal random_if_hand_card

  - name: VERCA
    image: 29_verca
    effects:
      - discard card self | hand
      - draw(2)

  - name: MARTIN
    image: 29_martin
    equip:
      - martin

  - name: TUCTUC
    image: 29_tuctuc
    equip:
      - tuctuc

  - name: MIKI
    image: 29_miki
    equip:
      - miki

  - name: LIBOR
    image: 29_libor
    equip:
      - libor

  - name: ELIS
    image: 29_elis
    responses:
      - elis card self | hand
      - missed

  # SKUPINA 3: DOCASNE ZAKOMENTOVANE PRO TEST
  # - name: HOROUS
  #   image: 29_horous
  # - name: VUDCE
  #   image: 29_vudce
  # - name: JEDNORUCKA_RIZEK
  #   image: 29_jednorucka_rizek
  # - name: PETUNA
  #   image: 29_petuna
  # - name: SMIG
  #   image: 29_smig
  # - name: CYRIL
  #   image: 29_cyril
  # - name: VENA
  #   image: 29_vena
  # - name: HELENA
  #   image: 29_helena
  # - name: SIMI
  #   image: 29_simi
  # - name: EL_BAGITO
  #   image: 29_el_bagito
  # - name: KRECEK
  #   image: 29_krecek
  # - name: EDIE
  #   image: 29_edie
  # - name: KOTEL
  #   image: 29_kotel
  # - name: TERMIT
  #   image: 29_termit
  # - name: SITEJ
  #   image: 29_sitej
  # - name: BUDHA
  #   image: 29_budha