character:
  - name: BIG_SPENCER
    image: 06_bigspencer
    equip:
      - big_spencer
      - initial_cards(5)
    tags:
      - max_hp(9)
  - name: FLINT_WESTWOOD
    image: 06_flintwestwood
    effects:
      - max_usages(1)
      - none card self | hand
      - none random_if_hand_card notself | hand
    mth_effect: flint_westwood(1,2)
  - name: GARY_LOOTER
    image: 06_garylooter
    equip:
      - gary_looter
    tags:
      - max_hp(5)
  - name: GREYGORY_DECK
    image: 06_greygorydeck
    responses:
      - can_play_card
      - greygory_deck
    equip:
      - greygory_deck
  - name: JOHN_PAIN
    image: 06_johnpain
    equip:
      - john_pain
  - name: LEE_VAN_KLIFF
    image: 06_leevankliff
    equip:
      - leevankliff
    modifier: leevankliff
    effects:
      - discard card self | hand used_bang
  - name: TEREN_KILL
    image: 06_terenkill
    equip:
      - teren_kill
    tags:
      - max_hp(3)
  - name: YOUL_GRINNER
    image: 06_youlgrinner
    equip:
      - youl_grinner