#ifndef __GREATTRAINROBBERY_EFFECTS_H__
#define __GREATTRAINROBBERY_EFFECTS_H__

#include "benny_brawler.h"
#include "cactus.h"
#include "cattle_truck.h"
#include "circus_wagon.h"
#include "dining_car.h"
#include "dragoon.h"
#include "evaded.h"
#include "evan_babbit.h"
#include "express_car.h"
#include "full_steam.h"
#include "ironhorse.h"
#include "leland.h"
#include "lounge_car.h"
#include "lumber_flatcar.h"
#include "knife_revolver.h"
#include "manuelita.h"
#include "mail_car.h"
#include "map.h"
#include "moneybag.h"
#include "most_wanted.h"
#include "next_stop.h"
#include "prisoner_car.h"
#include "private_car.h"
#include "refund.h"
#include "ruleset.h"
#include "shade_oconnor.h"
#include "skip_player.h"
#include "strongbox.h"
#include "switch_cards.h"
#include "traincost.h"

#endif