#ifndef __FRONTIER_EFFECTS_H_
#define __FRONTIER_EFFECTS_H_

#include "alexander_noon.h"
#include "ballad.h"
#include "caleb_brew.h"
#include "cattle_drive.h"
#include "cayenne_chee.h"
#include "chinatown.h"
#include "cholera.h"
#include "chuck_wagon.h"
#include "coffee.h"
#include "coffin.h"
#include "companion.h"
#include "coyotes.h"
#include "falcon.h"
#include "fishing.h"
#include "hawken.h"
#include "josey_strong.h"
#include "josiah_tung.h"
#include "pioneers.h"
#include "posse.h"
#include "ray_owe.h"
#include "ruleset.h"
#include "slocum.h"
#include "scorpion.h"
#include "shango_brothers.h"
#include "stampede.h"
#include "steve_tengo.h"
#include "tarantula_juice.h"
#include "trap.h"

#endif