#ifndef __LEGENDS_EFFECTS_H__
#define __LEGENDS_EFFECTS_H__

#include "become_legend.h"
#include "black_jack.h"
#include "borderlands.h"
#include "bottleneck.h"
#include "chuck_a_luck.h"
#include "el_gringo.h"
#include "fifty_guns.h"
#include "for_a_few_cards_more.h"
#include "jesse_jones.h"
#include "jourdonnais.h"
#include "kit_carlson.h"
#include "last_hero.h"
#include "lucky_duke.h"
#include "man_with_no_name.h"
#include "paul_regret.h"
#include "pedro_ramirez.h"
#include "perform_feat.h"
#include "quick_death.h"
#include "rose_doolan.h"
#include "ruleset.h"
#include "scrugs_ballad.h"
#include "sid_ketchum.h"
#include "slab_the_killer.h"
#include "train_to_yooma.h"
#include "vulture_sam.h"
#include "wounded_pride.h"
#include "wilhelm_scream.h"

#endif